[server]
maxUploadSize = 2

[client]
showSidebarNavigation = false

[theme]
base = "dark"
primaryColor = "#19C3E6"
backgroundColor = "#050E17"
secondaryBackgroundColor = "#101F30"
textColor = "#F1F5F9"
